name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign reviewers
        if: github.event.pull_request.user.login == 'chesthyeon'
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/auto-assign.yml